server {
    listen 80;
    listen [::]:80;
    server_name map.starst.site;

    location ^~ /.well-known/acme-challenge/ {
        root /home/ubuntu/starmap;
        try_files $uri =404;
    }

    location / {
        return 404;
    }
}